#cloud-config

# ssh_genkeytypes: [ed25519]

apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    k8s.list:
      keyid: 'DE15B14486CD377B9E876E1A234654DA9A296436'
      keyserver: 'https://prod-cdn.packages.k8s.io/repositories/isv:/kubernetes:/core:/stable:/v1.28/deb/Release.key'
      source: deb [signed-by=$KEY_FILE] https://prod-cdn.packages.k8s.io/repositories/isv:/kubernetes:/core:/stable:/v1.28/deb/ /

packages:
- apt-transport-https
- ca-certificates
- gpg
- curl
- gnupg-agent
- software-properties-common
- containerd.io
- kubelet
- kubeadm
- kubectl

runcmd:
- ["/etc/helper/init"]

write_files:

- path: /etc/helper/init
  owner: root:root
  permissions: '0700'
  content: |
    #!/bin/bash

    netplan apply
    modprobe br_netfilter
    echo 1 > /proc/sys/net/ipv4/ip_forward
    systemctl stop apparmor
    systemctl disable apparmor
    systemctl restart containerd.service
    kubeadm completion bash > /etc/bash_completion.d/kubeadm
    kubectl completion bash > /etc/bash_completion.d/kubectl

- path: /etc/containerd/config.toml
  content: |
    Version = 2
    [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
      SystemdCgroup = true
    [plugins.cri]
      sandbox_image = "registry.k8s.io/pause:3.9"

- path: /etc/modules-load.d/k8s.conf
  content: |
    br_netfilter
    overlay

- path: /etc/sysctl.d/99-z- k8s.conf
  content: |
    net.ipv4.ip_forward = 1
    net.bridge.bridge-nf-call-iptables = 1
    net.bridge.bridge-nf-call-ip6tables = 1

- path: /usr/local/bin/takeover-kube-config
  owner: root:root
  permissions: '0777'
  content: |
    mkdir -p $HOME/.kube
    sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    sudo chown $(id -u):$(id -g) $HOME/.kube/config

- path: /etc/netplan/10-custom.yaml
  content: |
    network:
      version: 2
      ethernets:
          eth1:
              dhcp4: no
              match:
                  macaddress: "52:54:00:4b:ab:ce"
              addresses: [10.13.31.2/24]
